### ISSUE TITLE
Изучить и найти информацию о возможности использования виртуальных адаптеров 

### ISSUE THREAD

**Issue by KocheshkovAA** [OSLL/tello-dev#26]
Задача: Изучить и найти информацию о возможности использования виртуальных адаптеров Wi-Fi для работы с несколькими дронами в режиме роя на одном устройстве. Предполагается, что при подключении к одной Wi-Fi сети демодулятор в Wi-Fi приемнике может "глушить" или отфильтровывать пакеты с других сетей. Также необходимо учитывать ограничения в ширине канала Wi-Fi сетей и возможные ограничения оборудования в поддержке широкой полосы сигнала. 

Необходимо найти статьи, документацию или примеры, которые могут помочь в решении данной проблемы.

Результат оформить в wiki.

**Comment by vgnlkn** [comment]
[WIKI-Страница](https://github.com/OSLL/tello-dev/wiki/%D0%92%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B0%D0%B4%D0%B0%D0%BF%D1%82%D0%B5%D1%80%D0%B0-WIFI-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D0%BC-%D0%B4%D1%80%D0%BE%D0%BD%D0%B0%D0%BC)
