### ISSUE TITLE
Сформулировать список закупки оборудования

### ISSUE THREAD

**Issue by KocheshkovAA** [OSLL/tello-dev#34]
Сформулировать список закупки оборудования в виде wiki страницы. Дать ссылки на оборудование, указать цену.

**Comment by vgnlkn** [comment]
https://github.com/OSLL/tello-dev/wiki/%D0%A4%D0%B8%D0%B7%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE
