### ISSUE TITLE
Написать инструкцию на компиляцию драйверов

### ISSUE THREAD

**Issue by KocheshkovAA** [OSLL/tello-dev#40]
Для выбора адаптера необходимо доказать, что он будет работать с Raspberry Pi.
    Нужно дать инструкцию как запустить, а лучше докер образ, в котором все будет компилиться.
    Можно просто найти готовое решение в качестве док-ва.
    Нужно найти способ проверить запуск на arm архитектуре (в лаборатория, эмуляторы и т.д.).

**Comment by vgnlkn** [comment]
Больше не требуется т.к. драйвера для закупленного адаптера предустановлены в ОС, в том числе и в Raspberry Pi
