### ISSUE TITLE
Указать версии базовых образов

### ISSUE THREAD

**Issue by KocheshkovAA** [OSLL/tello-dev#64]
Унифицировать используемые образы. Использовать сразу python образ (очень максимально желательно alpine или slim)
Задать общий образ для node и server? (возможно и networking)

**Comment by vgnlkn** [comment]
Использовать сразу python-образ не получится, поскольку зависимость jsonrpcclient, которая есть в каждом образе требует установки rust. Самостоятельная установка раста в python-образ ведет только к увеличению его объема и времени сборки. Переход на python-образы будет возможен при отказе от jsonrpc и использовании ros.
